INSERT INTO project (id, project_name, difficulty, version, department_id, created_at, updated_at)
VALUES
    (1, 'Hệ thống quản lý nhân sự', 'Dễ', 1.0, 1, NOW(), NOW()),
    (2, 'Ứng dụng thương mại điện tử', 'Trung bình', 2.1, 2, NOW(), NOW()),
    (3, 'AI Chatbot hỗ trợ khách hàng', 'Khó', 3.0, 3, NOW(), NOW()),
    (4, 'Website đặt vé xem phim', 'Trung bình', 1.5, 1, NOW(), NOW()),
    (5, 'Quản lý kho hàng', 'Dễ', 1.2, 2, NOW(), NOW()),
    (6, 'Ứng dụng đặt xe', 'Khó', 2.8, 3, NOW(), NOW()),
    (7, 'Hệ thống CRM', 'Trung bình', 1.9, 1, NOW(), NOW()),
    (8, 'Phần mềm kế toán', 'Khó', 3.2, 2, NOW(), NOW()),
    (9, 'Website học trực tuyến', 'Dễ', 1.0, 3, NOW(), NOW()),
    (10, 'Ứng dụng đặt đồ ăn', 'Trung bình', 2.5, 1, NOW(), NOW()),
    (11, 'Quản lý nhà hàng', 'Khó', 3.1, 2, NOW(), NOW()),
    (12, 'Hệ thống đặt phòng khách sạn', 'Dễ', 1.3, 3, NOW(), NOW()),
    (13, 'Ứng dụng quản lý dự án', 'Trung bình', 2.0, 1, NOW(), NOW()),
    (14, 'Hệ thống theo dõi tài chính', 'Khó', 3.5, 2, NOW(), NOW()),
    (15, 'Website tin tức', 'Dễ', 1.1, 3, NOW(), NOW()),
    (16, 'Ứng dụng chăm sóc sức khỏe', 'Trung bình', 2.3, 1, NOW(), NOW()),
    (17, 'Hệ thống kiểm soát truy cập', 'Khó', 3.7, 2, NOW(), NOW()),
    (18, 'Ứng dụng quản lý học sinh', 'Dễ', 1.4, 3, NOW(), NOW()),
    (19, 'Phần mềm quản lý tài sản', 'Trung bình', 2.6, 1, NOW(), NOW()),
    (20, 'Hệ thống phân tích dữ liệu', 'Khó', 4.0, 2, NOW(), NOW());
